### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by ghost** [aaron-santos/robinson#7]
Running under Linux Ubuntu 18.04 (java -jar robinson.jar)
`java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
`
`Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at zaffre.font$font_data.invokeStatic(font.cljc:137)
	at zaffre.font$font_data.invoke(font.cljc:125)
	at zaffre.font.TTFFont.glyph_graphics(font.cljc:356)
	at zaffre.glterminal$create_terminal$fn__27968.invoke(glterminal.clj:1030)
	at clojure.core$mapv$fn__8088.invoke(core.clj:6832)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$mapv.invokeStatic(core.clj:6823)
	at clojure.core$mapv.invoke(core.clj:6823)
	at zaffre.glterminal$create_terminal.invokeStatic(glterminal.clj:1025)
	at zaffre.glterminal$create_terminal.invoke(glterminal.clj:964)
	at robinson.autoreloadcore$_main$fn__29873.invoke(autoreloadcore.clj:83)
	at robinson.main$setup.invokeStatic(main.clj:236)
	at robinson.main$setup.invoke(main.clj:105)
	at robinson.main$setup.invokeStatic(main.clj:122)
	at robinson.main$setup.invoke(main.clj:105)
	at clojure.lang.Var.invoke(Var.java:381)
	at robinson.autoreloadcore$_main.invokeStatic(autoreloadcore.clj:81)
	at robinson.autoreloadcore$_main.invoke(autoreloadcore.clj:65)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at robinson.autoreloadcore.main(Unknown Source)
`

**Comment by aaron-santos** [comment]
Does running it as `./robinson.jar` work for you?

I'll apply this fix

https://github.com/apache/felix/pull/114

for those who wish to use their own jvms.
