### ISSUE TITLE
[OpenGL version?] GLFW error: 65543 GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by Bryum** [aaron-santos/robinson#8]
I suspect that the below output upon running 'lein run' is due to my OpenGL version (2.1; maximum on this older hardware, running Manjaro 18). Perhaps you intend Robinson to only run with newer OGL; but I thought I'd mention this, in case you could/wanted to increase OGL compatibility. Or it may be a different issue entirely. Thanks, and have fun.

OpenGL info:
```
glxinfo | grep 'version'
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 18.3.2
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

output of 'lein run'
```
Warning: implicit hook found: lein-autoreload.plugin/hooks 
Hooks are deprecated and will be removed in a future version.
Reflection warning, /tmp/form-init8066145483564459285.clj:1:912 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
Reflection warning, alandipert/enduro.clj:128:23 - call to java.io.FileOutputStream ctor can't be resolved.
Reflection warning, alandipert/enduro.clj:135:19 - reference to field toPath can't be resolved.
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.player, being replaced by: #'robinson.player/format
Reflection warning, robinson/viewport.clj:264:24 - call to java.lang.Exception ctor can't be resolved.
Reflection warning, robinson/viewport.clj:267:24 - call to java.lang.Exception ctor can't be resolved.
Reflection warning, robinson/prism.clj:135:16 - call to static method abs on java.lang.Math can't be resolved (argument types: unknown).
Reflection warning, robinson/prism.clj:135:30 - call to static method abs on java.lang.Math can't be resolved (argument types: unknown).
graph.clj:266 recur arg for primitive local: Tcost is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: Tcost
Reflection warning, rockpick/core.clj:19:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, robinson/dungeons/pirateship.cljc:21:88 - reference to field getName can't be resolved.
Reflection warning, robinson/dungeons/pirateship.cljc:23:31 - reference to field getPath can't be resolved.
Reflection warning, robinson/dungeons/pirateship.cljc:24:74 - reference to field getPath can't be resolved.
Reflection warning, robinson/dungeons/temple.cljc:384:44 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
Reflection warning, robinson/dungeons/temple.cljc:385:44 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
Reflection warning, robinson/dungeons/temple.cljc:384:44 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
Reflection warning, robinson/dungeons/temple.cljc:385:44 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
Reflection warning, robinson/worldgen.clj:92:16 - call to static method abs on java.lang.Math can't be resolved (argument types: unknown).
Reflection warning, robinson/worldgen.clj:92:30 - call to static method abs on java.lang.Math can't be resolved (argument types: unknown).
Reflection warning, robinson/worldgen.clj:530:1 - reference to field close can't be resolved.
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.endgame, being replaced by: #'robinson.endgame/format
Reflection warning, clojure/math/numeric_tower.clj:231:23 - reference to field numerator can't be resolved.
Reflection warning, clojure/math/numeric_tower.clj:232:18 - reference to field denominator can't be resolved.
Reflection warning, clojure/math/numeric_tower.clj:246:20 - reference to field numerator can't be resolved.
Reflection warning, clojure/math/numeric_tower.clj:246:7 - call to java.math.BigDecimal ctor can't be resolved.
Reflection warning, clojure/math/numeric_tower.clj:247:20 - reference to field denominator can't be resolved.
Reflection warning, clojure/math/numeric_tower.clj:247:7 - call to java.math.BigDecimal ctor can't be resolved.
WARNING: format already refers to: #'clojure.core/format in namespace: tinter.core, being replaced by: #'tinter.core/format
Reflection warning, zaffre/util.cljc:46:26 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
Reflection warning, zaffre/util.cljc:46:43 - call to static method abs on java.lang.Math can't be resolved (argument types: java.lang.Number).
WARNING: cycle already refers to: #'clojure.core/cycle in namespace: zaffre.util, being replaced by: #'zaffre.util/cycle
WARNING: sequence already refers to: #'clojure.core/sequence in namespace: zaffre.util, being replaced by: #'zaffre.util/sequence
Reflection warning, clj_http/util.clj:67:31 - reference to field read can't be resolved.
Reflection warning, clj_http/core.clj:319:40 - call to method setConnectionManager can't be resolved (target class is unknown).
Reflection warning, clj_http/core.clj:320:40 - call to method setRedirectStrategy can't be resolved (target class is unknown).
Reflection warning, clj_http/core.clj:330:7 - call to method setCacheConfig on org.apache.http.impl.client.HttpClientBuilder can't be resolved (no such method).
Reflection warning, clj_http/core.clj:522:42 - reference to field getCacheResponseStatus on org.apache.http.client.protocol.HttpClientContext can't be resolved.
Reflection warning, clj_http/client.clj:105:15 - reference to field available can't be resolved.
Reflection warning, zaffre/imageutil.clj:28:19 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:28:40 - reference to field position on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:32:11 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:34:44 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:39:5 - call to static method stbi_image_free on org.lwjgl.stb.STBImage can't be resolved (argument types: java.lang.Object).
Reflection warning, zaffre/imageutil.clj:110:3 - call to static method stbi_write_png on org.lwjgl.stb.STBImageWrite can't be resolved (argument types: unknown, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, long).
Reflection warning, zaffre/imageutil.clj:136:25 - reference to field slice can't be resolved.
Reflection warning, zaffre/imageutil.clj:136:17 - call to method limit can't be resolved (target class is unknown).
Reflection warning, zaffre/imageutil.clj:137:7 - call to method put can't be resolved (target class is unknown).
Reflection warning, zaffre/imageutil.clj:148:33 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:149:33 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:150:7 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:151:7 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:148:33 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:149:33 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:150:7 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:151:7 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:153:3 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:154:3 - call to method position on java.lang.Object can't be resolved (no such method).
Reflection warning, zaffre/imageutil.clj:155:3 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:156:3 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:233:28 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:234:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:235:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:236:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:234:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:235:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:236:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:238:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:245:22 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:246:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:247:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:248:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:249:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:246:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:247:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:248:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:249:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:250:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:257:22 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:258:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:259:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:260:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:261:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:262:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:258:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:259:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:260:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:261:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:262:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:263:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:272:30 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:273:28 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:274:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:275:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:276:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:277:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:278:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:279:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:274:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:275:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:276:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:277:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:278:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:279:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:281:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:288:28 - reference to field limit on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:289:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:290:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:291:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:292:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:293:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:294:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:295:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:289:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:290:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:291:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:292:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:293:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:294:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:295:9 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:296:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:301:24 - reference to field position can't be resolved.
Reflection warning, zaffre/imageutil.clj:301:3 - call to method position can't be resolved (target class is unknown).
Reflection warning, zaffre/imageutil.clj:326:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:328:11 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:326:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:328:11 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:326:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:328:11 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:326:15 - reference to field get on java.lang.Object can't be resolved.
Reflection warning, zaffre/imageutil.clj:328:11 - call to method put on java.nio.ByteBuffer can't be resolved (argument types: unknown).
Reflection warning, zaffre/imageutil.clj:330:5 - reference to field flip on java.lang.Object can't be resolved.
Reflection warning, zaffre/font.cljc:100:35 - reference to field toFile on java.lang.Object can't be resolved.
Reflection warning, zaffre/font.cljc:100:35 - reference to field toFile can't be resolved.
Reflection warning, zaffre/font.cljc:119:22 - call to java.io.File ctor can't be resolved.
Reflection warning, robinson/font.clj:40:31 - reference to field getName can't be resolved.
Reflection warning, robinson/font.clj:44:36 - reference to field getPath can't be resolved.
Reflection warning, robinson/font.clj:49:13 - reference to field listFiles can't be resolved.
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.describe, being replaced by: #'robinson.describe/format
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.combat, being replaced by: #'robinson.combat/format
Reflection warning, robinson/combat.clj:220:10 - call to java.lang.Exception ctor can't be resolved.
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.startgame, being replaced by: #'robinson.startgame/format
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.crafting, being replaced by: #'robinson.crafting/format
WARNING: vector already refers to: #'clojure.core/vector in namespace: clj-tiny-astar.path, being replaced by: #'clj-tuple/vector
WARNING: hash-map already refers to: #'clojure.core/hash-map in namespace: clj-tiny-astar.path, being replaced by: #'clj-tuple/hash-map
WARNING: vector already refers to: #'clojure.core/vector in namespace: clj-tiny-astar.util, being replaced by: #'clj-tuple/vector
WARNING: hash-map already refers to: #'clojure.core/hash-map in namespace: clj-tiny-astar.util, being replaced by: #'clj-tuple/hash-map
Reflection warning, clj_tiny_astar/path.cljc:14:3 - call to static method abs on java.lang.Math can't be resolved (argument types: unknown).
WARNING: format already refers to: #'clojure.core/format in namespace: robinson.update, being replaced by: #'robinson.update/format
Reflection warning, robinson/update.clj:59:5 - reference to field delete on java.lang.Object can't be resolved.
Reflection warning, robinson/update.clj:59:5 - reference to field delete can't be resolved.
Reflection warning, robinson/update.clj:931:20 - call to method indexOf can't be resolved (target class is unknown).
Reflection warning, robinson/update.clj:1675:20 - call to method indexOf can't be resolved (target class is unknown).
Reflection warning, robinson/update.clj:1695:20 - call to method indexOf can't be resolved (target class is unknown).
Reflection warning, robinson/update.clj:1944:20 - call to method indexOf can't be resolved (target class is unknown).
Reflection warning, robinson/update.clj:2554:9 - reference to field exists can't be resolved.
Reflection warning, overtone/at_at.clj:134:3 - reference to field shutdownNow can't be resolved.
Reflection warning, overtone/at_at.clj:142:3 - reference to field shutdown can't be resolved.
Reflection warning, overtone/at_at.clj:149:23 - reference to field isCancelled can't be resolved.
Reflection warning, overtone/at_at.clj:150:23 - reference to field isDone can't be resolved.
Reflection warning, overtone/at_at.clj:149:23 - reference to field isCancelled can't be resolved.
Reflection warning, overtone/at_at.clj:150:23 - reference to field isDone can't be resolved.
Reflection warning, overtone/at_at.clj:279:7 - call to method cancel can't be resolved (target class is unknown).
Reflection warning, clojure_watch/core.clj:33:32 - call to static method aset on clojure.lang.RT can't be resolved (argument types: unknown, int, unknown).
Reflection warning, clojure_watch/core.clj:58:29 - reference to field isDirectory can't be resolved.
Reflection warning, clojure_watch/core.clj:77:32 - reference to field take can't be resolved.
Reflection warning, clojure_watch/core.clj:80:40 - reference to field pollEvents can't be resolved.
Reflection warning, clojure_watch/core.clj:81:52 - reference to field kind on java.lang.Object can't be resolved.
Reflection warning, clojure_watch/core.clj:81:52 - reference to field name can't be resolved.
Reflection warning, clojure_watch/core.clj:84:44 - reference to field context on java.lang.Object can't be resolved.
Reflection warning, clojure_watch/core.clj:84:44 - call to method resolve on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure_watch/core.clj:89:32 - reference to field reset can't be resolved.
Reflection warning, clojure_watch/core.clj:81:52 - reference to field kind can't be resolved.
Reflection warning, clojure_watch/core.clj:81:52 - reference to field name can't be resolved.
Reflection warning, clojure_watch/core.clj:84:44 - reference to field context can't be resolved.
Reflection warning, clojure_watch/core.clj:84:44 - call to method resolve on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure_watch/core.clj:89:32 - reference to field reset can't be resolved.
Reflection warning, robinson/main.clj:53:1 - reference to field toPath can't be resolved.
Reflection warning, robinson/main.clj:53:1 - reference to field toPath can't be resolved.
Reflection warning, robinson/main.clj:53:1 - reference to field close can't be resolved.
Reflection warning, robinson/main.clj:137:11 - reference to field exists can't be resolved.
Reflection warning, robinson/main.clj:138:18 - reference to field exists can't be resolved.
Reflection warning, robinson/main.clj:143:47 - reference to field getName can't be resolved.
Reflection warning, robinson/main.clj:148:93 - reference to field getPath can't be resolved.
Reflection warning, robinson/main.clj:149:55 - reference to field getPath can't be resolved.
Reflection warning, robinson/main.clj:154:43 - reference to field isDirectory can't be resolved.
Reflection warning, robinson/main.clj:155:37 - reference to field listFiles can't be resolved.
Reflection warning, robinson/main.clj:156:32 - reference to field exists can't be resolved.
Reflection warning, robinson/main.clj:157:36 - reference to field exists can't be resolved.
Reflection warning, robinson/main.clj:160:36 - reference to field exists can't be resolved.
Reflection warning, robinson/main.clj:166:41 - reference to field exists can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:87:38 - reference to field recv on java.lang.Object can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:88:46 - call to method recv on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure/tools/nrepl/middleware/load_file.clj:93:27 - call to method send on java.lang.Object can't be resolved (no such method).
Reflection warning, clojure/tools/nrepl/server.clj:143:33 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, clojure/tools/nrepl/server.clj:145:25 - call to java.net.InetSocketAddress ctor can't be resolved.
19-02-25 10:51:35 ##### INFO [robinson.main:200] - Using font settings {:name "Boxy 16", :linux-font "fonts/Boxy/Boxy.ttf", :macosx-font "fonts/Boxy/Boxy.ttf", :windows-font "fonts/Boxy/Boxy.ttf", :font-size 16, :transparent true}
19-02-25 10:51:35 ##### INFO [robinson.main:224] - Creating terminal in thread: main
19-02-25 10:51:35 ##### INFO [robinson.main:225] - Loaded data: (:atmo :ui :gameplay :keyboard-controls :help)
19-02-25 10:51:35 ##### INFO [zaffre.glterminal:1002] - group-id->index {:app 0}
19-02-25 10:51:35 ##### INFO [zaffre.glterminal:1003] - group-map {:app #object[clojure.lang.Ref 0x509debfe {:status :ready, :val {:gl-blend-equation :gl-func-add, :gl-blend-func [:gl-one :gl-one-minus-src-alpha], :id :app, :layers [:map :features :shading :ui], :columns 80, :rows 24, :pos [0 0], :font #object[clojure.core$partial$fn__5824 0x1a64f46b "clojure.core$partial$fn__5824@1a64f46b"]}}]}
19-02-25 10:51:35 ##### INFO [zaffre.glterminal:1004] - layer-id->group {:map #object[clojure.lang.Ref 0x509debfe {:status :ready, :val {:gl-blend-equation :gl-func-add, :gl-blend-func [:gl-one :gl-one-minus-src-alpha], :id :app, :layers [:map :features :shading :ui], :columns 80, :rows 24, :pos [0 0], :font #object[clojure.core$partial$fn__5824 0x1a64f46b "clojure.core$partial$fn__5824@1a64f46b"]}}], :features #object[clojure.lang.Ref 0x509debfe {:status :ready, :val {:gl-blend-equation :gl-func-add, :gl-blend-func [:gl-one :gl-one-minus-src-alpha], :id :app, :layers [:map :features :shading :ui], :columns 80, :rows 24, :pos [0 0], :font #object[clojure.core$partial$fn__5824 0x1a64f46b "clojure.core$partial$fn__5824@1a64f46b"]}}], :shading #object[clojure.lang.Ref 0x509debfe {:status :ready, :val {:gl-blend-equation :gl-func-add, :gl-blend-func [:gl-one :gl-one-minus-src-alpha], :id :app, :layers [:map :features :shading :ui], :columns 80, :rows 24, :pos [0 0], :font #object[clojure.core$partial$fn__5824 0x1a64f46b "clojure.core$partial$fn__5824@1a64f46b"]}}], :ui #object[clojure.lang.Ref 0x509debfe {:status :ready, :val {:gl-blend-equation :gl-func-add, :gl-blend-func [:gl-one :gl-one-minus-src-alpha], :id :app, :layers [:map :features :shading :ui], :columns 80, :rows 24, :pos [0 0], :font #object[clojure.core$partial$fn__5824 0x1a64f46b "clojure.core$partial$fn__5824@1a64f46b"]}}]}
19-02-25 10:51:35 ##### INFO [zaffre.glterminal:1005] - layer-id->index {:map 0, :features 1, :shading 2, :ui 3}
19-02-25 10:51:36 ##### ERROR [zaffre.glterminal:239] - GLFW error: 65543 GLX: Failed to create context: GLXBadFBConfig
Exception in thread "main" Syntax error compiling at (/tmp/form-init8066145483564459285.clj:1:73).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:98)
	at org.lwjgl.glfw.GLFW.glfwSetWindowPos(GLFW.java:1923)
	at zaffre.glterminal$init_display.invokeStatic(glterminal.clj:257)
	at zaffre.glterminal$init_display.invoke(glterminal.clj:233)
	at zaffre.glterminal$create_terminal.invokeStatic(glterminal.clj:1019)
	at zaffre.glterminal$create_terminal.invoke(glterminal.clj:967)
	at robinson.autoreloadcore$_main$fn__34099.invoke(autoreloadcore.clj:83)
	at robinson.main$setup.invokeStatic(main.clj:230)
	at robinson.main$setup.invoke(main.clj:118)
	at robinson.main$setup.invokeStatic(main.clj:135)
	at robinson.main$setup.invoke(main.clj:118)
	at clojure.lang.Var.invoke(Var.java:384)
	at robinson.autoreloadcore$_main.invokeStatic(autoreloadcore.clj:81)
	at robinson.autoreloadcore$_main.invoke(autoreloadcore.clj:65)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval142.invokeStatic(form-init8066145483564459285.clj:1)
	at user$eval142.invoke(form-init8066145483564459285.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
```

**Comment by aaron-santos** [comment]
Thanks for the debug output. Your hunch is correct. The minimum OpenGL version is 3.2. At the very least there should be a dialog explaining the situation.

Depends on: https://github.com/aaron-santos/zaffre/issues/9
